### ISSUE TITLE
Empty replacements not possible.

### ISSUE THREAD

**Issue by chripu** [axe312ger/responsive_svg#4]
In `ResponsiveSvgTwigExtension.php` on line 76 use `if (isset($mappings[$path]) && ($mappings[$path]['replacement'] !== NULL)) {` instead of `if (!empty($mappings[$path]['replacement'])) {` to support empty replacements im combination with inline SVG and IE.

Otherwise there is no way to remove the path from the href to make it work in IE.
```html
<use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/themes/custom/xyz/images/iconstack.svg#search"></use>
```
```html
<use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#search"></use>
```

**Comment by axe312ger** [comment]
Evil IE 😓 

A PR would be awesome, do not work with PHP since more than one year now, have no Drupal env here to test any changes.

All the best,
Benedikt

**Comment by chripu** [comment]
Hi Benedikt,
can you add a new release here: https://www.drupal.org/project/responsive_svg
Thanks,
Christian
